package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1



/**
 * ActividadviajeJn generated by hbm2java
 */
public class ActividadviajeJn  implements java.io.Serializable {


     private ActividadviajeJnId id;

    public ActividadviajeJn() {
    }

    public ActividadviajeJn(ActividadviajeJnId id) {
       this.id = id;
    }
   
    public ActividadviajeJnId getId() {
        return this.id;
    }
    
    public void setId(ActividadviajeJnId id) {
        this.id = id;
    }




}


