package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1



/**
 * ActividadJn generated by hbm2java
 */
public class ActividadJn  implements java.io.Serializable {


     private ActividadJnId id;

    public ActividadJn() {
    }

    public ActividadJn(ActividadJnId id) {
       this.id = id;
    }
   
    public ActividadJnId getId() {
        return this.id;
    }
    
    public void setId(ActividadJnId id) {
        this.id = id;
    }




}


