package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ActividadJnId generated by hbm2java
 */
public class ActividadJnId  implements java.io.Serializable {


     private String jnOperation;
     private String jnOracleUser;
     private Date jnDatetime;
     private String jnNotes;
     private String jnAppln;
     private BigDecimal jnSession;
     private BigDecimal idactividad;
     private BigDecimal cursoIdcurso;
     private BigDecimal tipoactividad;

    public ActividadJnId() {
    }

	
    public ActividadJnId(String jnOperation, String jnOracleUser, Date jnDatetime, BigDecimal idactividad, BigDecimal cursoIdcurso, BigDecimal tipoactividad) {
        this.jnOperation = jnOperation;
        this.jnOracleUser = jnOracleUser;
        this.jnDatetime = jnDatetime;
        this.idactividad = idactividad;
        this.cursoIdcurso = cursoIdcurso;
        this.tipoactividad = tipoactividad;
    }
    public ActividadJnId(String jnOperation, String jnOracleUser, Date jnDatetime, String jnNotes, String jnAppln, BigDecimal jnSession, BigDecimal idactividad, BigDecimal cursoIdcurso, BigDecimal tipoactividad) {
       this.jnOperation = jnOperation;
       this.jnOracleUser = jnOracleUser;
       this.jnDatetime = jnDatetime;
       this.jnNotes = jnNotes;
       this.jnAppln = jnAppln;
       this.jnSession = jnSession;
       this.idactividad = idactividad;
       this.cursoIdcurso = cursoIdcurso;
       this.tipoactividad = tipoactividad;
    }
   
    public String getJnOperation() {
        return this.jnOperation;
    }
    
    public void setJnOperation(String jnOperation) {
        this.jnOperation = jnOperation;
    }
    public String getJnOracleUser() {
        return this.jnOracleUser;
    }
    
    public void setJnOracleUser(String jnOracleUser) {
        this.jnOracleUser = jnOracleUser;
    }
    public Date getJnDatetime() {
        return this.jnDatetime;
    }
    
    public void setJnDatetime(Date jnDatetime) {
        this.jnDatetime = jnDatetime;
    }
    public String getJnNotes() {
        return this.jnNotes;
    }
    
    public void setJnNotes(String jnNotes) {
        this.jnNotes = jnNotes;
    }
    public String getJnAppln() {
        return this.jnAppln;
    }
    
    public void setJnAppln(String jnAppln) {
        this.jnAppln = jnAppln;
    }
    public BigDecimal getJnSession() {
        return this.jnSession;
    }
    
    public void setJnSession(BigDecimal jnSession) {
        this.jnSession = jnSession;
    }
    public BigDecimal getIdactividad() {
        return this.idactividad;
    }
    
    public void setIdactividad(BigDecimal idactividad) {
        this.idactividad = idactividad;
    }
    public BigDecimal getCursoIdcurso() {
        return this.cursoIdcurso;
    }
    
    public void setCursoIdcurso(BigDecimal cursoIdcurso) {
        this.cursoIdcurso = cursoIdcurso;
    }
    public BigDecimal getTipoactividad() {
        return this.tipoactividad;
    }
    
    public void setTipoactividad(BigDecimal tipoactividad) {
        this.tipoactividad = tipoactividad;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ActividadJnId) ) return false;
		 ActividadJnId castOther = ( ActividadJnId ) other; 
         
		 return ( (this.getJnOperation()==castOther.getJnOperation()) || ( this.getJnOperation()!=null && castOther.getJnOperation()!=null && this.getJnOperation().equals(castOther.getJnOperation()) ) )
 && ( (this.getJnOracleUser()==castOther.getJnOracleUser()) || ( this.getJnOracleUser()!=null && castOther.getJnOracleUser()!=null && this.getJnOracleUser().equals(castOther.getJnOracleUser()) ) )
 && ( (this.getJnDatetime()==castOther.getJnDatetime()) || ( this.getJnDatetime()!=null && castOther.getJnDatetime()!=null && this.getJnDatetime().equals(castOther.getJnDatetime()) ) )
 && ( (this.getJnNotes()==castOther.getJnNotes()) || ( this.getJnNotes()!=null && castOther.getJnNotes()!=null && this.getJnNotes().equals(castOther.getJnNotes()) ) )
 && ( (this.getJnAppln()==castOther.getJnAppln()) || ( this.getJnAppln()!=null && castOther.getJnAppln()!=null && this.getJnAppln().equals(castOther.getJnAppln()) ) )
 && ( (this.getJnSession()==castOther.getJnSession()) || ( this.getJnSession()!=null && castOther.getJnSession()!=null && this.getJnSession().equals(castOther.getJnSession()) ) )
 && ( (this.getIdactividad()==castOther.getIdactividad()) || ( this.getIdactividad()!=null && castOther.getIdactividad()!=null && this.getIdactividad().equals(castOther.getIdactividad()) ) )
 && ( (this.getCursoIdcurso()==castOther.getCursoIdcurso()) || ( this.getCursoIdcurso()!=null && castOther.getCursoIdcurso()!=null && this.getCursoIdcurso().equals(castOther.getCursoIdcurso()) ) )
 && ( (this.getTipoactividad()==castOther.getTipoactividad()) || ( this.getTipoactividad()!=null && castOther.getTipoactividad()!=null && this.getTipoactividad().equals(castOther.getTipoactividad()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getJnOperation() == null ? 0 : this.getJnOperation().hashCode() );
         result = 37 * result + ( getJnOracleUser() == null ? 0 : this.getJnOracleUser().hashCode() );
         result = 37 * result + ( getJnDatetime() == null ? 0 : this.getJnDatetime().hashCode() );
         result = 37 * result + ( getJnNotes() == null ? 0 : this.getJnNotes().hashCode() );
         result = 37 * result + ( getJnAppln() == null ? 0 : this.getJnAppln().hashCode() );
         result = 37 * result + ( getJnSession() == null ? 0 : this.getJnSession().hashCode() );
         result = 37 * result + ( getIdactividad() == null ? 0 : this.getIdactividad().hashCode() );
         result = 37 * result + ( getCursoIdcurso() == null ? 0 : this.getCursoIdcurso().hashCode() );
         result = 37 * result + ( getTipoactividad() == null ? 0 : this.getTipoactividad().hashCode() );
         return result;
   }   


}


