package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private BigDecimal idactividad;
     private BigDecimal cursoIdcurso;
     private BigDecimal tipoactividad;

    public Actividad() {
    }

    public Actividad(BigDecimal idactividad, BigDecimal cursoIdcurso, BigDecimal tipoactividad) {
       this.idactividad = idactividad;
       this.cursoIdcurso = cursoIdcurso;
       this.tipoactividad = tipoactividad;
    }
   
    public BigDecimal getIdactividad() {
        return this.idactividad;
    }
    
    public void setIdactividad(BigDecimal idactividad) {
        this.idactividad = idactividad;
    }
    public BigDecimal getCursoIdcurso() {
        return this.cursoIdcurso;
    }
    
    public void setCursoIdcurso(BigDecimal cursoIdcurso) {
        this.cursoIdcurso = cursoIdcurso;
    }
    public BigDecimal getTipoactividad() {
        return this.tipoactividad;
    }
    
    public void setTipoactividad(BigDecimal tipoactividad) {
        this.tipoactividad = tipoactividad;
    }




}


