package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ActividadviajeJnId generated by hbm2java
 */
public class ActividadviajeJnId  implements java.io.Serializable {


     private String jnOperation;
     private String jnOracleUser;
     private Date jnDatetime;
     private String jnNotes;
     private String jnAppln;
     private BigDecimal jnSession;
     private BigDecimal idactividadviaje;
     private String nombre;
     private String descripcion;
     private Date fechainicio;
     private Date fechatermino;
     private BigDecimal tipoactividadviaje;

    public ActividadviajeJnId() {
    }

	
    public ActividadviajeJnId(String jnOperation, String jnOracleUser, Date jnDatetime, BigDecimal idactividadviaje, BigDecimal tipoactividadviaje) {
        this.jnOperation = jnOperation;
        this.jnOracleUser = jnOracleUser;
        this.jnDatetime = jnDatetime;
        this.idactividadviaje = idactividadviaje;
        this.tipoactividadviaje = tipoactividadviaje;
    }
    public ActividadviajeJnId(String jnOperation, String jnOracleUser, Date jnDatetime, String jnNotes, String jnAppln, BigDecimal jnSession, BigDecimal idactividadviaje, String nombre, String descripcion, Date fechainicio, Date fechatermino, BigDecimal tipoactividadviaje) {
       this.jnOperation = jnOperation;
       this.jnOracleUser = jnOracleUser;
       this.jnDatetime = jnDatetime;
       this.jnNotes = jnNotes;
       this.jnAppln = jnAppln;
       this.jnSession = jnSession;
       this.idactividadviaje = idactividadviaje;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.fechainicio = fechainicio;
       this.fechatermino = fechatermino;
       this.tipoactividadviaje = tipoactividadviaje;
    }
   
    public String getJnOperation() {
        return this.jnOperation;
    }
    
    public void setJnOperation(String jnOperation) {
        this.jnOperation = jnOperation;
    }
    public String getJnOracleUser() {
        return this.jnOracleUser;
    }
    
    public void setJnOracleUser(String jnOracleUser) {
        this.jnOracleUser = jnOracleUser;
    }
    public Date getJnDatetime() {
        return this.jnDatetime;
    }
    
    public void setJnDatetime(Date jnDatetime) {
        this.jnDatetime = jnDatetime;
    }
    public String getJnNotes() {
        return this.jnNotes;
    }
    
    public void setJnNotes(String jnNotes) {
        this.jnNotes = jnNotes;
    }
    public String getJnAppln() {
        return this.jnAppln;
    }
    
    public void setJnAppln(String jnAppln) {
        this.jnAppln = jnAppln;
    }
    public BigDecimal getJnSession() {
        return this.jnSession;
    }
    
    public void setJnSession(BigDecimal jnSession) {
        this.jnSession = jnSession;
    }
    public BigDecimal getIdactividadviaje() {
        return this.idactividadviaje;
    }
    
    public void setIdactividadviaje(BigDecimal idactividadviaje) {
        this.idactividadviaje = idactividadviaje;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechatermino() {
        return this.fechatermino;
    }
    
    public void setFechatermino(Date fechatermino) {
        this.fechatermino = fechatermino;
    }
    public BigDecimal getTipoactividadviaje() {
        return this.tipoactividadviaje;
    }
    
    public void setTipoactividadviaje(BigDecimal tipoactividadviaje) {
        this.tipoactividadviaje = tipoactividadviaje;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ActividadviajeJnId) ) return false;
		 ActividadviajeJnId castOther = ( ActividadviajeJnId ) other; 
         
		 return ( (this.getJnOperation()==castOther.getJnOperation()) || ( this.getJnOperation()!=null && castOther.getJnOperation()!=null && this.getJnOperation().equals(castOther.getJnOperation()) ) )
 && ( (this.getJnOracleUser()==castOther.getJnOracleUser()) || ( this.getJnOracleUser()!=null && castOther.getJnOracleUser()!=null && this.getJnOracleUser().equals(castOther.getJnOracleUser()) ) )
 && ( (this.getJnDatetime()==castOther.getJnDatetime()) || ( this.getJnDatetime()!=null && castOther.getJnDatetime()!=null && this.getJnDatetime().equals(castOther.getJnDatetime()) ) )
 && ( (this.getJnNotes()==castOther.getJnNotes()) || ( this.getJnNotes()!=null && castOther.getJnNotes()!=null && this.getJnNotes().equals(castOther.getJnNotes()) ) )
 && ( (this.getJnAppln()==castOther.getJnAppln()) || ( this.getJnAppln()!=null && castOther.getJnAppln()!=null && this.getJnAppln().equals(castOther.getJnAppln()) ) )
 && ( (this.getJnSession()==castOther.getJnSession()) || ( this.getJnSession()!=null && castOther.getJnSession()!=null && this.getJnSession().equals(castOther.getJnSession()) ) )
 && ( (this.getIdactividadviaje()==castOther.getIdactividadviaje()) || ( this.getIdactividadviaje()!=null && castOther.getIdactividadviaje()!=null && this.getIdactividadviaje().equals(castOther.getIdactividadviaje()) ) )
 && ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) )
 && ( (this.getDescripcion()==castOther.getDescripcion()) || ( this.getDescripcion()!=null && castOther.getDescripcion()!=null && this.getDescripcion().equals(castOther.getDescripcion()) ) )
 && ( (this.getFechainicio()==castOther.getFechainicio()) || ( this.getFechainicio()!=null && castOther.getFechainicio()!=null && this.getFechainicio().equals(castOther.getFechainicio()) ) )
 && ( (this.getFechatermino()==castOther.getFechatermino()) || ( this.getFechatermino()!=null && castOther.getFechatermino()!=null && this.getFechatermino().equals(castOther.getFechatermino()) ) )
 && ( (this.getTipoactividadviaje()==castOther.getTipoactividadviaje()) || ( this.getTipoactividadviaje()!=null && castOther.getTipoactividadviaje()!=null && this.getTipoactividadviaje().equals(castOther.getTipoactividadviaje()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getJnOperation() == null ? 0 : this.getJnOperation().hashCode() );
         result = 37 * result + ( getJnOracleUser() == null ? 0 : this.getJnOracleUser().hashCode() );
         result = 37 * result + ( getJnDatetime() == null ? 0 : this.getJnDatetime().hashCode() );
         result = 37 * result + ( getJnNotes() == null ? 0 : this.getJnNotes().hashCode() );
         result = 37 * result + ( getJnAppln() == null ? 0 : this.getJnAppln().hashCode() );
         result = 37 * result + ( getJnSession() == null ? 0 : this.getJnSession().hashCode() );
         result = 37 * result + ( getIdactividadviaje() == null ? 0 : this.getIdactividadviaje().hashCode() );
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
         result = 37 * result + ( getFechainicio() == null ? 0 : this.getFechainicio().hashCode() );
         result = 37 * result + ( getFechatermino() == null ? 0 : this.getFechatermino().hashCode() );
         result = 37 * result + ( getTipoactividadviaje() == null ? 0 : this.getTipoactividadviaje().hashCode() );
         return result;
   }   


}


