package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1



/**
 * ActividadaportesJn generated by hbm2java
 */
public class ActividadaportesJn  implements java.io.Serializable {


     private ActividadaportesJnId id;

    public ActividadaportesJn() {
    }

    public ActividadaportesJn(ActividadaportesJnId id) {
       this.id = id;
    }
   
    public ActividadaportesJnId getId() {
        return this.id;
    }
    
    public void setId(ActividadaportesJnId id) {
        this.id = id;
    }




}


