package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Colegio generated by hbm2java
 */
public class Colegio  implements java.io.Serializable {


     private BigDecimal idcolegio;
     private String nombre;
     private String direccion;
     private BigDecimal telefono;
     private BigDecimal comunaIdcomuna;

    public Colegio() {
    }

	
    public Colegio(BigDecimal idcolegio, BigDecimal comunaIdcomuna) {
        this.idcolegio = idcolegio;
        this.comunaIdcomuna = comunaIdcomuna;
    }
    public Colegio(BigDecimal idcolegio, String nombre, String direccion, BigDecimal telefono, BigDecimal comunaIdcomuna) {
       this.idcolegio = idcolegio;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.comunaIdcomuna = comunaIdcomuna;
    }
   
    public BigDecimal getIdcolegio() {
        return this.idcolegio;
    }
    
    public void setIdcolegio(BigDecimal idcolegio) {
        this.idcolegio = idcolegio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public BigDecimal getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(BigDecimal telefono) {
        this.telefono = telefono;
    }
    public BigDecimal getComunaIdcomuna() {
        return this.comunaIdcomuna;
    }
    
    public void setComunaIdcomuna(BigDecimal comunaIdcomuna) {
        this.comunaIdcomuna = comunaIdcomuna;
    }




}


