package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private BigDecimal idcurso;
     private String nombre;
     private BigDecimal colegio;

    public Curso() {
    }

	
    public Curso(BigDecimal idcurso, BigDecimal colegio) {
        this.idcurso = idcurso;
        this.colegio = colegio;
    }
    public Curso(BigDecimal idcurso, String nombre, BigDecimal colegio) {
       this.idcurso = idcurso;
       this.nombre = nombre;
       this.colegio = colegio;
    }
   
    public BigDecimal getIdcurso() {
        return this.idcurso;
    }
    
    public void setIdcurso(BigDecimal idcurso) {
        this.idcurso = idcurso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getColegio() {
        return this.colegio;
    }
    
    public void setColegio(BigDecimal colegio) {
        this.colegio = colegio;
    }




}


