package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Origen generated by hbm2java
 */
public class Origen  implements java.io.Serializable {


     private BigDecimal idorigen;
     private BigDecimal pais;

    public Origen() {
    }

    public Origen(BigDecimal idorigen, BigDecimal pais) {
       this.idorigen = idorigen;
       this.pais = pais;
    }
   
    public BigDecimal getIdorigen() {
        return this.idorigen;
    }
    
    public void setIdorigen(BigDecimal idorigen) {
        this.idorigen = idorigen;
    }
    public BigDecimal getPais() {
        return this.pais;
    }
    
    public void setPais(BigDecimal pais) {
        this.pais = pais;
    }




}


