package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Permiso generated by hbm2java
 */
public class Permiso  implements java.io.Serializable {


     private BigDecimal idpermiso;
     private String nombre;
     private String descripcion;
     private BigDecimal perfil;

    public Permiso() {
    }

	
    public Permiso(BigDecimal idpermiso, BigDecimal perfil) {
        this.idpermiso = idpermiso;
        this.perfil = perfil;
    }
    public Permiso(BigDecimal idpermiso, String nombre, String descripcion, BigDecimal perfil) {
       this.idpermiso = idpermiso;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.perfil = perfil;
    }
   
    public BigDecimal getIdpermiso() {
        return this.idpermiso;
    }
    
    public void setIdpermiso(BigDecimal idpermiso) {
        this.idpermiso = idpermiso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(BigDecimal perfil) {
        this.perfil = perfil;
    }




}


