package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1



/**
 * PermisoJn generated by hbm2java
 */
public class PermisoJn  implements java.io.Serializable {


     private PermisoJnId id;

    public PermisoJn() {
    }

    public PermisoJn(PermisoJnId id) {
       this.id = id;
    }
   
    public PermisoJnId getId() {
        return this.id;
    }
    
    public void setId(PermisoJnId id) {
        this.id = id;
    }




}


