package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PermisoJnId generated by hbm2java
 */
public class PermisoJnId  implements java.io.Serializable {


     private String jnOperation;
     private String jnOracleUser;
     private Date jnDatetime;
     private String jnNotes;
     private String jnAppln;
     private BigDecimal jnSession;
     private BigDecimal idpermiso;
     private String nombre;
     private String descripcion;
     private BigDecimal perfil;

    public PermisoJnId() {
    }

	
    public PermisoJnId(String jnOperation, String jnOracleUser, Date jnDatetime, BigDecimal idpermiso, BigDecimal perfil) {
        this.jnOperation = jnOperation;
        this.jnOracleUser = jnOracleUser;
        this.jnDatetime = jnDatetime;
        this.idpermiso = idpermiso;
        this.perfil = perfil;
    }
    public PermisoJnId(String jnOperation, String jnOracleUser, Date jnDatetime, String jnNotes, String jnAppln, BigDecimal jnSession, BigDecimal idpermiso, String nombre, String descripcion, BigDecimal perfil) {
       this.jnOperation = jnOperation;
       this.jnOracleUser = jnOracleUser;
       this.jnDatetime = jnDatetime;
       this.jnNotes = jnNotes;
       this.jnAppln = jnAppln;
       this.jnSession = jnSession;
       this.idpermiso = idpermiso;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.perfil = perfil;
    }
   
    public String getJnOperation() {
        return this.jnOperation;
    }
    
    public void setJnOperation(String jnOperation) {
        this.jnOperation = jnOperation;
    }
    public String getJnOracleUser() {
        return this.jnOracleUser;
    }
    
    public void setJnOracleUser(String jnOracleUser) {
        this.jnOracleUser = jnOracleUser;
    }
    public Date getJnDatetime() {
        return this.jnDatetime;
    }
    
    public void setJnDatetime(Date jnDatetime) {
        this.jnDatetime = jnDatetime;
    }
    public String getJnNotes() {
        return this.jnNotes;
    }
    
    public void setJnNotes(String jnNotes) {
        this.jnNotes = jnNotes;
    }
    public String getJnAppln() {
        return this.jnAppln;
    }
    
    public void setJnAppln(String jnAppln) {
        this.jnAppln = jnAppln;
    }
    public BigDecimal getJnSession() {
        return this.jnSession;
    }
    
    public void setJnSession(BigDecimal jnSession) {
        this.jnSession = jnSession;
    }
    public BigDecimal getIdpermiso() {
        return this.idpermiso;
    }
    
    public void setIdpermiso(BigDecimal idpermiso) {
        this.idpermiso = idpermiso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(BigDecimal perfil) {
        this.perfil = perfil;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermisoJnId) ) return false;
		 PermisoJnId castOther = ( PermisoJnId ) other; 
         
		 return ( (this.getJnOperation()==castOther.getJnOperation()) || ( this.getJnOperation()!=null && castOther.getJnOperation()!=null && this.getJnOperation().equals(castOther.getJnOperation()) ) )
 && ( (this.getJnOracleUser()==castOther.getJnOracleUser()) || ( this.getJnOracleUser()!=null && castOther.getJnOracleUser()!=null && this.getJnOracleUser().equals(castOther.getJnOracleUser()) ) )
 && ( (this.getJnDatetime()==castOther.getJnDatetime()) || ( this.getJnDatetime()!=null && castOther.getJnDatetime()!=null && this.getJnDatetime().equals(castOther.getJnDatetime()) ) )
 && ( (this.getJnNotes()==castOther.getJnNotes()) || ( this.getJnNotes()!=null && castOther.getJnNotes()!=null && this.getJnNotes().equals(castOther.getJnNotes()) ) )
 && ( (this.getJnAppln()==castOther.getJnAppln()) || ( this.getJnAppln()!=null && castOther.getJnAppln()!=null && this.getJnAppln().equals(castOther.getJnAppln()) ) )
 && ( (this.getJnSession()==castOther.getJnSession()) || ( this.getJnSession()!=null && castOther.getJnSession()!=null && this.getJnSession().equals(castOther.getJnSession()) ) )
 && ( (this.getIdpermiso()==castOther.getIdpermiso()) || ( this.getIdpermiso()!=null && castOther.getIdpermiso()!=null && this.getIdpermiso().equals(castOther.getIdpermiso()) ) )
 && ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) )
 && ( (this.getDescripcion()==castOther.getDescripcion()) || ( this.getDescripcion()!=null && castOther.getDescripcion()!=null && this.getDescripcion().equals(castOther.getDescripcion()) ) )
 && ( (this.getPerfil()==castOther.getPerfil()) || ( this.getPerfil()!=null && castOther.getPerfil()!=null && this.getPerfil().equals(castOther.getPerfil()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getJnOperation() == null ? 0 : this.getJnOperation().hashCode() );
         result = 37 * result + ( getJnOracleUser() == null ? 0 : this.getJnOracleUser().hashCode() );
         result = 37 * result + ( getJnDatetime() == null ? 0 : this.getJnDatetime().hashCode() );
         result = 37 * result + ( getJnNotes() == null ? 0 : this.getJnNotes().hashCode() );
         result = 37 * result + ( getJnAppln() == null ? 0 : this.getJnAppln().hashCode() );
         result = 37 * result + ( getJnSession() == null ? 0 : this.getJnSession().hashCode() );
         result = 37 * result + ( getIdpermiso() == null ? 0 : this.getIdpermiso().hashCode() );
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
         result = 37 * result + ( getPerfil() == null ? 0 : this.getPerfil().hashCode() );
         return result;
   }   


}


