package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1



/**
 * Tiposervicio generated by hbm2java
 */
public class Tiposervicio  implements java.io.Serializable {


     private TiposervicioId id;

    public Tiposervicio() {
    }

    public Tiposervicio(TiposervicioId id) {
       this.id = id;
    }
   
    public TiposervicioId getId() {
        return this.id;
    }
    
    public void setId(TiposervicioId id) {
        this.id = id;
    }




}


