package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TiposervicioId generated by hbm2java
 */
public class TiposervicioId  implements java.io.Serializable {


     private BigDecimal idtiposervicio;
     private String nombre;
     private String descripcion;

    public TiposervicioId() {
    }

	
    public TiposervicioId(BigDecimal idtiposervicio) {
        this.idtiposervicio = idtiposervicio;
    }
    public TiposervicioId(BigDecimal idtiposervicio, String nombre, String descripcion) {
       this.idtiposervicio = idtiposervicio;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public BigDecimal getIdtiposervicio() {
        return this.idtiposervicio;
    }
    
    public void setIdtiposervicio(BigDecimal idtiposervicio) {
        this.idtiposervicio = idtiposervicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TiposervicioId) ) return false;
		 TiposervicioId castOther = ( TiposervicioId ) other; 
         
		 return ( (this.getIdtiposervicio()==castOther.getIdtiposervicio()) || ( this.getIdtiposervicio()!=null && castOther.getIdtiposervicio()!=null && this.getIdtiposervicio().equals(castOther.getIdtiposervicio()) ) )
 && ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) )
 && ( (this.getDescripcion()==castOther.getDescripcion()) || ( this.getDescripcion()!=null && castOther.getDescripcion()!=null && this.getDescripcion().equals(castOther.getDescripcion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdtiposervicio() == null ? 0 : this.getIdtiposervicio().hashCode() );
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         result = 37 * result + ( getDescripcion() == null ? 0 : this.getDescripcion().hashCode() );
         return result;
   }   


}


