package Entidades;
// Generated 02-10-2017 21:55:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Tipoactividadviaje generated by hbm2java
 */
public class Tipoactividadviaje  implements java.io.Serializable {


     private BigDecimal idtipoactividadviaje;
     private String nombre;
     private String descripcion;

    public Tipoactividadviaje() {
    }

	
    public Tipoactividadviaje(BigDecimal idtipoactividadviaje) {
        this.idtipoactividadviaje = idtipoactividadviaje;
    }
    public Tipoactividadviaje(BigDecimal idtipoactividadviaje, String nombre, String descripcion) {
       this.idtipoactividadviaje = idtipoactividadviaje;
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
    public BigDecimal getIdtipoactividadviaje() {
        return this.idtipoactividadviaje;
    }
    
    public void setIdtipoactividadviaje(BigDecimal idtipoactividadviaje) {
        this.idtipoactividadviaje = idtipoactividadviaje;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


